[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorlog>=6.9.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyside6>=6.9.1",
    "python-dotenv>=1.1.1",
]
